name: ci

on:
  push:
    branches:
      - main
    paths:
      - "**.drawio"
      - .github/workflows/ci.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Export draw.io files to PNG
        uses: rlespinasse/drawio-export-action@v2
        if: contains(github.ref, 'refs/heads/main')
        with:
          format: png
          transparent: true
          output: drawio-assets

      - name: Install MkDocs with material theme
        run: pip install mkdocs-material
        if: contains(github.ref, 'refs/heads/main')

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        if: contains(github.ref, 'refs/heads/main')

      - name: Commit draw.io exported files
        uses: stefanzweifel/git-auto-commit-action@v4
        if: contains(github.ref, 'refs/heads/main')
        with:
          commit_message: "docs: sync draw.io exported files"
          commit_user_name: "${{ github.actor }}"
          commit_user_email: "${{ github.actor }}@users.noreply.github.com"
          commit_author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
